version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "test-sam-template"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-17v3cu6173l1x"
s3_prefix = "test-sam-template"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
