AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

# Globals that shared sam resources e.g, below applied to all Functions.
Globals:
  Function:
    Timeout: 3

Description: >
  CRC Backend app

  Cloud resume challenge backend application.

Resources:
  CRCBackendLambdaFunction:
    Type: AWS::Serverless::Function
    Properties: 
      CodeUri: src/
      Handler: app.handler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CRCDynamodbTable
        - AWSLambdaBasicExecutionRole

      Environment:
        Variables:
          TABLE_NAME: !Ref CRCDynamodbTable

      Events:
        ApiEvent:
          Type: Api 
          Properties:
            Path: /count
            Method: POST
            RestApiId:
              Ref: CRCBackendApiGateway

  CRCBackendApiGateway:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: prod
      CorsConfiguration:
        AllowCredentials: true
        AllowMethods:
          - GET
          - POST
        AllowHeaders:
          - CONTENT-TYPE
        AllowOrigins:
          - "*"
        MaxAge: 600
      # Cors:
      #   AllowMethods: "'POST, GET'"
      #   AllowHeaders: "'CONTENT-TYPE'"
      #   AllowOrigin: "'*'"
      #   MaxAge: "'600'"

  CRCDynamodbTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      Tags:
        Department: Engineering
        AppType: Cloud Resume challenge serverless

  # CRCDynamodbTable:
  #   Type: AWS::DynamoDB::Table
  #   Properties: 
  #     AttributeDefinitions: 
  #       - AttributeName: VisitorCountID
  #         AttributeType: S
      
  #       - AttributeName: Count
  #         AttributeType: S
      
  #     KeySchema:
  #       - AttributeName: VisitorCountID
  #         KeyType: HASH
        
  #       - AttributeName: Count
  #         KeyType: RANGE
  #     BillingMode: PAY_PER_REQUEST
  